-------------------------------------------------------------------------------
-- fir_filter.vhd
--
-- Direct-form FIR filter, fully parallel (one multiply-accumulate per tap,
-- combined into a single registered adder tree per clock cycle).
--
-- y[n] = sum_{i=0}^{NUM_TAPS-1} COEFFS(i) * x[n-i]
--
-- Coefficients are Q15 fixed point (16-bit signed, value = real_coeff * 32768),
-- generated by python/generate_coeffs.py (16-tap low-pass, Hamming window,
-- cutoff = 0.2 * Nyquist). Input samples are plain 16-bit signed integers.
-- The accumulator is right-shifted by (COEFF_WIDTH-1) bits to rescale back
-- to the input's Q0 format, then saturated to DATA_WIDTH bits.
--
-- Latency: 1 clock cycle from valid_in to valid_out (registered output).
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fir_filter is
  generic (
    NUM_TAPS    : integer := 16;
    DATA_WIDTH  : integer := 16;
    COEFF_WIDTH : integer := 16;
    ACC_WIDTH   : integer := 40
  );
  port (
    clk       : in  std_logic;
    rst_n     : in  std_logic;                                  -- async active-low reset
    data_in   : in  std_logic_vector(DATA_WIDTH-1 downto 0);     -- signed sample in
    valid_in  : in  std_logic;                                   -- new sample present
    data_out  : out std_logic_vector(DATA_WIDTH-1 downto 0);     -- signed sample out
    valid_out : out std_logic                                    -- data_out is valid
  );
end entity fir_filter;

architecture rtl of fir_filter is

  type coeff_array_t is array (0 to NUM_TAPS-1) of signed(COEFF_WIDTH-1 downto 0);
  type shift_array_t is array (0 to NUM_TAPS-1) of signed(DATA_WIDTH-1 downto 0);

  -- 16-tap low-pass FIR, cutoff = 0.2 * Nyquist, Hamming window
  -- Q15 fixed point (value = coeff * 32768); sum of taps = 32766 (~0.9999 DC gain)
  -- Generated by python/generate_coeffs.py -- regenerate there if you change
  -- NUM_TAPS or the cutoff frequency, and paste the new table in below.
  constant COEFFS : coeff_array_t := (
    0  => to_signed(  -114, COEFF_WIDTH),
    1  => to_signed(  -159, COEFF_WIDTH),
    2  => to_signed(  -139, COEFF_WIDTH),
    3  => to_signed(   291, COEFF_WIDTH),
    4  => to_signed(  1450, COEFF_WIDTH),
    5  => to_signed(  3284, COEFF_WIDTH),
    6  => to_signed(  5246, COEFF_WIDTH),
    7  => to_signed(  6524, COEFF_WIDTH),
    8  => to_signed(  6524, COEFF_WIDTH),
    9  => to_signed(  5246, COEFF_WIDTH),
    10 => to_signed(  3284, COEFF_WIDTH),
    11 => to_signed(  1450, COEFF_WIDTH),
    12 => to_signed(   291, COEFF_WIDTH),
    13 => to_signed(  -139, COEFF_WIDTH),
    14 => to_signed(  -159, COEFF_WIDTH),
    15 => to_signed(  -114, COEFF_WIDTH)
  );

  signal shift_reg      : shift_array_t := (others => (others => '0'));
  signal acc            : signed(ACC_WIDTH-1 downto 0) := (others => '0');
  signal valid_out_reg  : std_logic := '0';

  -- Saturate a wide signed value down to `width` bits
  function saturate(v : signed; width : integer) return signed is
    variable max_v : signed(v'range) := (others => '0');
    variable min_v : signed(v'range) := (others => '0');
  begin
    max_v := resize(to_signed(2**(width-1) - 1, width), v'length);
    min_v := resize(to_signed(-(2**(width-1)), width), v'length);
    if v > max_v then
      return resize(max_v, width);
    elsif v < min_v then
      return resize(min_v, width);
    else
      return resize(v, width);
    end if;
  end function;

begin

  process(clk, rst_n)
    variable taps_now : shift_array_t;
    variable sum       : signed(ACC_WIDTH-1 downto 0);
  begin
    if rst_n = '0' then
      shift_reg     <= (others => (others => '0'));
      acc           <= (others => '0');
      valid_out_reg <= '0';
    elsif rising_edge(clk) then
      if valid_in = '1' then
        -- Tap window for this sample: newest sample first, then the
        -- previous NUM_TAPS-1 samples already sitting in shift_reg.
        taps_now(0) := signed(data_in);
        for i in 1 to NUM_TAPS-1 loop
          taps_now(i) := shift_reg(i-1);
        end loop;

        sum := (others => '0');
        for i in 0 to NUM_TAPS-1 loop
          sum := sum + (taps_now(i) * COEFFS(i));
        end loop;
        acc <= sum;

        shift_reg <= taps_now;
      end if;
      valid_out_reg <= valid_in;
    end if;
  end process;

  -- Rescale Q15 accumulator back to Q0 and saturate to DATA_WIDTH
  data_out  <= std_logic_vector(saturate(shift_right(acc, COEFF_WIDTH-1), DATA_WIDTH));
  valid_out <= valid_out_reg;

end architecture rtl;
